# Generated by Django 2.1.5 on 2020-07-02 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_salad'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salad',
            old_name='large',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='salad',
            name='small',
        ),
    ]
