# Generated by Django 2.1.5 on 2020-07-08 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_order_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_items',
            name='toppingID',
            field=models.IntegerField(default=0),
        ),
    ]
