# Generated by Django 2.1.5 on 2020-07-09 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_items_toppingid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_items',
            name='toppingID',
        ),
    ]
